name: Update addons table after merge

on:
  push:
    branches:
      - "20.0"
    paths-ignore:
      - "README.md"

permissions:
  contents: write

jobs:
  gen-addons-table:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run the manual hook to (re)generate the addons table
        run: pre-commit run -a --hook-stage manual oca-gen-addons-table
        continue-on-error: true
      - name: Commit & push if changed
        env:
          PUSH_URL: https://x-access-token:${{ secrets.PRIVATE_TOKEN }}@github.com/${{ github.repository }}.git
        run: |
          if ! git diff --quiet; then
            git config user.name  "noviat-ci-bot"
            git config user.email "bot+ci@noviat.com"
            git add -A
            git commit -m "update addons table"
            git remote set-url origin "$PUSH_URL"
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            git push origin HEAD:20.0
          fi
